
# default: &default
#   adapter: sqlite3
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000

# development:
#   <<: *default
#   database: db/development.sqlite3
  
  
# test:
#   <<: *default
#   database: db/test.sqlite3
#   pool: 50
#   timeout: 5000
  

# production:
#   <<: *default
#   database: db/production.sqlite3
#-------------------------------------------------------------------------OK-------------------------------------------

# default: &default
#   adapter: postgres
#   port : 5432
#   # encoding: unicode
#   # pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   username: <%= ENV['POSTGRES_USER'] %>
#   password: <%= ENV['POSTGRES_PASSWORD'] %>
#   host: localhost


default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: huy2108
  host: localhost

development:
  <<: *default
  database: sample_app_development

test:
  <<: *default
  database: sample_app_test

production:
  <<: *default
  database: sample_app_production
  # username: <%= ENV['POSTGRES_USER'] %>
  # password: <%= ENV['POSTGRES_PASSWORD'] %>
  username: postgres
  password: huy2108
  host: sample_app_production_host

  #----------------------------------------------------------------------------
# default: &default
#   adapter: sqlite3
#   pool: 5
#   timeout: 5000

# development:
#   <<: *default
#   database: db/development.sqlite3

# # Warning: The database defined as "test" will be erased and
# # re-generated from your development database when you run "rake".
# # Do not set this db to the same as development or production.
# test:
#   <<: *default
#   database: db/test.sqlite3

# production:
#   adapter: postgresql
#   encoding: unicode
#   # For details on connection pooling, see Rails configuration guide
#   # https://guides.rubyonrails.org/configuring.html#database-pooling
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   database: sample_app_production
#   username: sample_app
#   password: <%= ENV['SAMPLE_APP_DATABASE_PASSWORD'] %>